Repository redhat-developer/lsp4ij, pull requests merged in 2023-12, with the labels that each got.

#35 fix: fill LSP consoles with server which have no language mappings.
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerListConfigurable.java
Labels: bug

#37 feat: provide a base class for LSP command action
  src/main/java/com/redhat/devtools/lsp4ij/commands/LSPCommandAction.java
Labels: enhancement

#39 chore: remove reference to internal API com.intellij.ide.plugins.cl.PluginClassLoader
  src/main/java/com/redhat/devtools/lsp4ij/commands/GsonManager.java
Labels: debt

#44 feat: Use inlayhint factory to avoid declaring LSP codelens/inlayhint support in an external plugin
  README.md
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/AbstractLSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/LSPInlayHintProvidersFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/codelens/LSPCodelensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/inlayhint/LSPInlayHintsProvider.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#47 chore: use IJ SystemInfo
  src/main/java/com/redhat/devtools/lsp4ij/server/JavaProcessCommandBuilder.java
  src/main/java/com/redhat/devtools/lsp4ij/server/OS.java
Labels: enhancement

#57 fix: show inlayhint for EAP
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/LSPInlayHintProvidersFactory.java
Labels: bug

#59 fix: properly render markdown tables
  build.gradle.kts
  gradle.properties
  src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/MarkdownConverter.java
  src/test/java/com/redhat/devtools/lsp4ij/operations/documentation/MarkdownConverterTest.java
Labels: bug, hover

#61 fix: NPE when codeaction is a command
  src/main/java/com/redhat/devtools/lsp4ij/operations/codeactions/LSPLazyCodeActionIntentionAction.java
Labels: bug, codeaction

#62 refactor: move classes to definition package.
  docs/DeveloperGuide.md
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleView.java
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPTextConsoleBuilderImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerTreeNode.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/ContentTypeToLanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerLanguageMapping.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerMapping.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ExtensionLanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/LanguageMappingExtensionPointBean.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ServerExtensionPointBean.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerConfigurable.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerListConfigurable.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement
