Repository redhat-developer/lsp4ij, pull requests merged in 2024-12, with the labels that each got.

#656 chore: changelog for 0.8.1
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#661 fix: minor fix for client configuration
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java
  src/main/resources/messages/LanguageServerBundle.properties
Labels: enhancement

#663 feat: Omit word completions (by default) when there are completions from the language server (issue 638)
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement, completion

#649 fix: Allow requesting scalar values in workspace/configuration
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/client/SettingsHelper.java
  src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java
Labels: bug

#671 fix: register ProjectIndexingActivityHistoryListener on appFrameCreated
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingAppLifecycleListener.java
Labels: bug

#672 feat: initialize GeneralClientCapabilities
  src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
Labels: enhancement

#676 feat: Addendum for PR #665 to update `LSPSupport.md` for a new code folding demo and an explanation/demo for the code block provider
  docs/LSPSupport.md
  docs/images/lsp-support/codeBlockProvider.gif
  docs/images/lsp-support/textDocument_foldingRange.gif
Labels: documentation

#690 fix: ensure executing Query LSP implementation in ReadAction
  src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceImplementationsSearch.java
Labels: bug

#695 chore: bump to 0.9.0
  gradle.properties
Labels: documentation

#694 fix: Changed `file` to be `@Nullable` since a `null` value could be provided to the method
  src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileProvider.java
Labels: bug

#697 chore: changelog for 0.9.0
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#704 feat: add JSON Schema for rust-analyzer configuration
  src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
  src/main/resources/templates/rust-analyzer/initializationOptions.json
  src/main/resources/templates/rust-analyzer/settings.json
  src/main/resources/templates/rust-analyzer/settings.schema.json
Labels: enhancement, template-ls

#706 docs: Add jimmer dto lsp
  README.md
Labels: documentation

#717 docs: Add Vue JS docs
  docs/UserDefinedLanguageServer.md
  docs/user-defined-ls/vue-js-language-server.md
Labels: documentation, template-ls
