Repository redhat-developer/lsp4ij, pull requests merged in 2024-11, with the labels that each got.

#587 fix: compare two filenames before trying to rename the file
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
Labels: bug, rename

#591 chore: bump to 0.8.0-SNAPSHOT
  gradle.properties
Labels: build

#599 build: use gradle 4 in github actions
  .github/workflows/IJ-latest.yml
  .github/workflows/IJ.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: build

#600 fix: dont disable server when project is closed.
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
Labels: bug

#604 fix: Use Locale.ROOT for capitalizing / decapitalizing locale insensitive strings.
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/SeverityMapping.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
Labels: bug

#607 fix: Error while calling ModificationStampUtil.clearModificationStamp(editor)
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/CodeVisionEditorFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/FoldingEditorFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/InlayHintsEditorFeature.java
Labels: bug

#613 fix: send didOpen before refreshing editors after a project indexing
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/client/ProjectIndexingListener.java
Labels: bug

#616 fix: enable find usages.
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java
Labels: bug

#633 fix: remove using internal API ProjectIndexingActivityHistoryListener
  src/main/java/com/redhat/devtools/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
  src/main/java/com/redhat/devtools/lsp4ij/client/IndexAwareLanguageClient.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingAppLifecycleListener.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingDumbAndScanningStrategy.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingManager.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingOnlyDumbStrategy.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingStrategyBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTargetProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java
  src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyProviderBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java
  src/main/resources/META-INF/plugin.xml
Labels: bug

#642 feat: add SourceKit-LSP as template
  docs/UserDefinedLanguageServer.md
  docs/images/user-defined-ls/SourceKitLSPInLSPConsole.png
  docs/images/user-defined-ls/SourceKitLSPTemplate.png
  docs/images/user-defined-ls/SourceKitLSPTemplateMappings.png
  docs/user-defined-ls/sourcekit-lsp.md
  src/main/resources/templates/sourcekit-lsp/README.md
  src/main/resources/templates/sourcekit-lsp/initializationOptions.json
  src/main/resources/templates/sourcekit-lsp/settings.json
  src/main/resources/templates/sourcekit-lsp/template.json
Labels: enhancement, template-ls

#646 fix: minor fix for SourceToolkit-LSP doc
  docs/user-defined-ls/sourcekit-lsp.md
  src/main/resources/templates/sourcekit-lsp/README.md
Labels: bug, documentation, template-ls
