Repository redhat-developer/lsp4ij, pull requests merged in 2024-05, with the labels that each got.

#262 feat: Check each open file when adding a new LS definition
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java
Labels: enhancement

#277 refactor: don't store selected completion item in the singleton LSPCompletionContributor.
  docs/LSPSupport.md
  docs/images/lsp-support/completionItem_resolve_detail.png
  docs/images/lsp-support/completionItem_resolve_documentation.png
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java
Labels: refactoring

#282 feat: support showMessageRequest with notification
  docs/LSPSupport.md
  docs/UserGuide.md
  docs/images/LSPConsole.png
  docs/images/LSPConsole_Logs.png
  docs/images/lsp-support/window_showMessageRequest.png
  docs/images/lsp-support/window_showMessageRequest_Notification.png
  docs/images/lsp-support/window_showMessage_Notification.png
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerItem.java
  src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/LanguageServerBundle.properties
Labels: enhancement

#288 refactor: move SupportedFeatures into ClientCapabilitiesFactory
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
Labels: debt

#290 perf: Try to get document without read action
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/signatureHelp/LSPParameterInfoHandler.java
Labels: performance

#295 fix: Copy-and-paste error in intention description
  src/main/resources/intentionDescriptions/Refactor/description.html
Labels: bug

#296 test: provide LSP hover tests
  src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationHelper.java
  src/test/java/com/redhat/devtools/lsp4ij/features/documentation/TypeScriptHoverTest.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPHoverFixtureTestCase.java
Labels: hover, junit-test

#306 fix: don't use PluginAwareClassLoader#tryLoadingClass
  src/main/java/com/redhat/devtools/lsp4ij/JSONUtils.java
Labels: bug

#291 feat: go to implementation/references/declaration/type definition with menu
  docs/LSPSupport.md
  docs/images/lsp-support/textDocument_implementation_menu.png
  docs/images/lsp-support/textDocument_implementation_popup.png
  docs/images/lsp-support/textDocument_references_menu.png
  docs/images/lsp-support/textDocument_references_popup.png
  docs/images/user-defined-ls/TypeScriptServerDialog_Configuration.png
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/editor/ShowReferencesAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPDeclarationParams.java
  src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPDeclarationSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPGoToDeclarationAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPGoToImplementationAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPImplementationParams.java
  src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPImplementationSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPGoToReferenceAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPReferenceParams.java
  src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPReferenceSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPGoToTypeDefinitionAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPTypeDefinitionParams.java
  src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPTypeDefinitionSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageType.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/LanguageServerBundle.properties
Labels: references, declaration, typeDefinition, implementation

#309 fix: resolve additionalTextEdits if empty
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java
  src/main/resources/templates/rust-analyzer/initializationOptions.json
Labels: bug, completion

#310 feat: Support for labelDetails completionItem
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
Labels: enhancement, completion

#316 docs: add go demo
  docs/images/user-defined-ls/GoplsDemo.gif
  docs/user-defined-ls/gopls.md
  docs/user-defined-ls/typescript-language-server.md
Labels: documentation
