Repository redhat-developer/lsp4ij, pull requests merged in 2024-06, with the labels that each got.

#317 docs: improve go documentation
  docs/images/user-defined-ls/GoTextMate.png
  docs/images/user-defined-ls/GoplsInLSPConsole.png
  docs/images/user-defined-ls/GoplsTemplate.png
  docs/images/user-defined-ls/GoplsTemplateConfiguration.png
  docs/images/user-defined-ls/GoplsTemplateMappings.png
  docs/user-defined-ls/gopls.md
  src/main/resources/templates/gopls/README.md
Labels: documentation

#319 perf: LSP folding must be computed outside dumb
  src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java
Labels: performance, folding

#321 perf: don't process LSP hover while indexing(dumb)
  src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTargetProvider.java
Labels: performance, hover

#323 fix: show LSP console in IJ 2024.2
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/ApplicationUtils.java
Labels: bug, lsp-console

#320 perf: open one read action to consume LSP codelens
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
Labels: performance, codeLens

#330 fix: dont send workspace/didChangeConfiguration when server starts.
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
Labels: bug

#331 docs: add documentation for Rust Analyzer
  docs/UserDefinedLanguageServer.md
  docs/images/user-defined-ls/RustAnalyzerDemo.gif
  docs/images/user-defined-ls/RustAnalyzerInLSPConsole.png
  docs/images/user-defined-ls/RustAnalyzerTemplate.png
  docs/images/user-defined-ls/RustAnalyzerTemplateConfiguration.png
  docs/images/user-defined-ls/RustAnalyzerTemplateMappings.png
  docs/images/user-defined-ls/RustTextMate.png
  docs/user-defined-ls/rust-analyzer.md
  src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateDeserializer.java
  src/main/resources/templates/rust-analyzer/template.json
Labels: documentation, user-defined LS

#332 feat: use AllIcons.Json.Object for Struct completion item kind
  src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
Labels: enhancement, completion

#333 fix: fix test import for Windows OS
  src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateDeserializerTest.java
  src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManagerTest.java
Labels: bug, junit-test

#341 fix: prevent NPE in LSP console when switching projects
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
Labels: bug

#339 fix: send workspace/didChangeConfiguration with {} if configuration is empty
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageListener.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java
Labels: bug, user-defined LS

#347 fix: prevent from "implementation class is not specified" with documentMatcher
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/FileNamePatternMappingExtensionPointBean.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/FileTypeMappingExtensionPointBean.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/LanguageMappingExtensionPointBean.java
Labels: bug

#348 fix: rootUri must not end with a slash
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/server/StreamConnectionProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java
  src/test/java/com/redhat/devtools/lsp4ij/mock/MockConnectionProvider.java
Labels: bug

#329 feat: show notification error when command doesn't exist.
  src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/LSPCommandContext.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/LSPLazyCodeActionIntentionAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java
  src/main/resources/messages/LanguageServerBundle.properties
Labels: enhancement

#349 fix: prevent NPE when isEnabled is called from plugin ls definition
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ExtensionLanguageServerDefinition.java
Labels: bug

#357 feat: Diagnostic tags support
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
Labels: enhancement, diagnostic

#343 fix: use registration id to update workspace/didChangeWatchedFiles cache
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/features/files/watcher/FileSystemWatcherManager.java
  src/test/java/com/redhat/devtools/lsp4ij/features/files/FileSystemWatcherManagerTest.java
Labels: bug

#365 feat: display platform file icons on completion
  src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
Labels: enhancement, completion

#369 fix: don't break custom "Find Usages" (like Java)
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java
  src/main/resources/META-INF/plugin.xml
Labels: bug

#391 docs: Add `intellij-haskell-lsp` to "Who is using LSP4IJ?" section in README
  README.md
Labels: documentation
