Repository redhat-developer/lsp4ij, pull requests merged in 2024-01, with the labels that each got.

#65 docs: textDocument/documentColor support in action
  docs/LSPSupport.md
  docs/images/lsp-support/textDocument_documentColor.png
Labels: documentation, color

#74 fix: NPE when color is undefined.
  src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
  src/test/java/com/redhat/devtools/lsp4ij/ui/IconMapperTest.java
Labels: bug, color

#81 fix: wrong position for completion snippet without tabstops
  src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
Labels: bug, completion

#90 fix: Support publishDiagnostics as capability
  src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java
Labels: bug

#93 fix: decode URI if needed
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
Labels: bug

#95 fix: workspace/applyEdit must be executed in write action
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/resources/templates/node/typescript-language-server.md
Labels: bug

#102 feat: display source + code of LSP diagnostic as tooltip
  src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java
Labels: enhancement, diagnostic

#103 feat: support for diagnostic related informations.
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/hint/LSPNavigationLinkHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement, diagnostic

#111 feat: add eclipse.jdt.ls template (dev)
  src/main/resources/templates/java/jdt.ls.md
  src/main/resources/templates/java/lemminx.md
  src/main/resources/templates/template-ls.json
Labels: enhancement, template-ls

#117 feat: add scss support
  src/main/resources/templates/template-ls.json
Labels: enhancement

#129 build: update minimum required IJ version to 2022.3
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
Labels: build
