Repository redhat-developer/lsp4ij, pull requests merged in 2024-10, with the labels that each got.

#559 docs: add Intellij Gleam to list of projects
  README.md
Labels: documentation

#567 fix: hover dynamic options
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CodeActionCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CodeLensCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CompletionCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DeclarationCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DefinitionCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentColorCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentFormattingCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentHighlightCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentLinkCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentRangeFormattingCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentSymbolCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/FoldingRangeCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/HoverCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/ImplementationCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/InlayHintCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/ReferencesCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/RenameCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/SignatureHelpCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TypeDefinitionCapabilityRegistry.java
Labels: bug

#568 feat: add canStopServerByUser LSP client feature
  docs/LSPApi.md
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
Labels: enhancement, api-customization

#569 fix: triggered characters for completion/signatureHelp doesn't work with registerCapability
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPSignatureHelpFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPTypedHandlerDelegate.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CompletionCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/SignatureHelpCapabilityRegistry.java
Labels: bug

#573 chore: changelog for 0.7.0
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#576 fix: prevent from NPE CancellationSupport
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPFeatureSupport.java
Labels: bug

#581 fix: synchronized client features creation to avoid loosing register capability.
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCodeActionFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCodeLensFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDeclarationFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDefinitionFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentColorFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentHighlightFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentLinkFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentSymbolFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPFoldingRangeFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPFormattingFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPHoverFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPImplementationFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPInlayHintFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPReferencesFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPRenameFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPSignatureHelpFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPTypeDefinitionFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java
Labels: bug
