Repository redhat-developer/lsp4ij, pull requests merged in 2024-09, with the labels that each got.

#506 docs: Fix typo in code snippet in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#510 chore: clean telemetry code
  src/main/java/com/redhat/devtools/lsp4ij/internal/LSPPostStartupActivity.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/RedHatTelemetryService.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/TelemetryManager.java
  src/main/java/com/redhat/devtools/lsp4ij/telemetry/TelemetryEventName.java
  src/main/java/com/redhat/devtools/lsp4ij/telemetry/TelemetryService.java
  src/main/resources/META-INF/plugin.xml
Labels: debt

#511 fix: support case sensitive for completion item which doesn't define a text range
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
  src/test/java/com/redhat/devtools/lsp4ij/features/completion/ServerEnvCompletionTest.java
Labels: bug, completion

#515 fix: trim spaces for user defined ls command.
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/CommandUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java
  src/test/java/com/redhat/devtools/lsp4ij/server/definition/launching/CommandUtilsTest.java
Labels: bug

#524 chore: don't use internal ActionToolbarImpl
  src/main/java/com/redhat/devtools/lsp4ij/console/actions/ApplyLanguageServerSettingsAction.java
Labels: enhancement

#526 docs: Add `Ruff for PyCharm` to README.md
  README.md
Labels: documentation

#537 feat: improve document symbol + add doc
  docs/LSPSupport.md
  docs/images/lsp-support/textDocument_documentSymbol.gif
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolSupport.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement, document -symbols

#544 chore: use CompletableFuture to wait after sending didOpen notification.
  src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
Labels: enhancement

#546 chore: add changelog for 0.6.0
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#549 fix: NullPointerException from Find Usages action in IntelliJ using LSP4IJ 0.6.0
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
Labels: bug

#550 perf: cancel LSP highlight only if offset changed.
  src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java
Labels: performance, documentHighlight
