Repository redhat-developer/lsp4ij, pull requests merged in 2025-03, with the labels that each got.

#874 docs: add redscript intelliJ
  README.md
Labels: documentation

#875 docs: add angelscript language server for intellij
  README.md
Labels: documentation

#879 fix: don't use internal API
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugRunner.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/variables/providers/DefaultVariableRangeRegistrar.java
  src/main/resources/dap/templates/python-debugpy/template.json
Labels: bug

#883 feat: Add support for breadcrumbs and sticky lines (fixes #700)
  docs/LSPApi.md
  docs/LSPSupport.md
  docs/images/lsp-support/textDocument_documentSymbol_breadcrumbs.gif
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPBreadcrumbsFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticToken.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokenPsiElement.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensContainer.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensSingleRootFileViewProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedBreadcrumbsFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/jsonSchema/clientSettings.schema.json
  src/main/resources/templates/lemminx/clientSettings.json
  src/main/resources/templates/vscode-html-language-server/clientSettings.json
  src/test/java/com/redhat/devtools/lsp4ij/features/documentSymbol/TypeScriptBreadcrumbsProviderTest.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPBreadcrumbsProviderFixtureTestCase.java
Labels: enhancement, breadcrumbs

#886 fix: support for register semanticTokens capability with dynamic mode
  src/main/java/com/redhat/devtools/lsp4ij/LSPRequestConstants.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPSemanticTokensFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/SemanticTokensCapabilityRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java
Labels: bug, semantic tokens

#890 docs: add "Meet LSP4IJ, a new Debug Adapter Protocol for JetBrains-based IDEs" article.
  README.md
Labels: documentation

#891 chore: Bump to 0.12.0
  gradle.properties
Labels: build

#893 perf: Do not clear the document symbol cache when the view is disposed.
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
Labels: performance, documentSymbols

#900 perf: improve perf of language server is stopping when project is closed.
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
Labels: performance

#903 fix: fix flaky codelens
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensDataResult.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensEditorFactoryListener.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/PsiFileChangedException.java
Labels: bug, codeLens

#904 fix: Do not create alarm without coroutineScope: com.redhat.devtools.lsp4ij.features.codeLens.UnresolvedCodeLensViewportContext.<init>(UnresolvedCodeLensViewportContext.java:37)
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java
Labels: bug, codeLens

#905 perf: cancel LSP documentSymbol+semanticTokens only when file has changed
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java
Labels: performance, semantic tokens, documentSymbols

#909 fix: Ensured that the LSP4IJ usage element description provider doesn't return any value for non-LSP4IJ elements
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageElementDescriptionProvider.java
  src/main/resources/META-INF/plugin.xml
Labels: bug

#910 fix: do some performance improvement
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java
  src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
Labels: performance

#913 perf: use PsiFile instead of using VirtualFile
  src/main/java/com/redhat/devtools/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJEditorUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/EditorBehaviorFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingStrategyBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDocumentFeatureSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionTriggerTypedHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPEditorImprovementsTypedHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java
  src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPExtendWordSelectionHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceImplementationsSearch.java
  src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceTypeDeclarationProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPExternalReferencesFinder.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
  src/test/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractTypeScriptEditorImprovementsTest.java
  src/test/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensStructurelessFileViewProviderRegistrarTest.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPBreadcrumbsProviderFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPClientSideOnTypeFormattingFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeBlockProviderFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionClientConfigFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPFoldingRangeFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPFormattingFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPRenameFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPSelectionRangeFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPSelectionersFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPSemanticTokensFileViewProviderFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPServerSideOnTypeFormattingFixtureTestCase.java
Labels: performance

#915 fix: use language substitor
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingManager.java
Labels: bug

#917 fix: fix mapping, client config, debug suspend changes
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java
Labels: bug

#923 fix: remove isInexAll to avoid freeze.
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
Labels: performance

#925 perf: Simplify access to client config information (fixes #912)
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java
Labels: performance

#927 fix: create a fake psi file for document link
  src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkPsiElement.java
Labels: bug

#929 perf: disable call of processExternalReferences
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
Labels: performance

#935 fix: Added caching of the file view provider's one file.
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
Labels: bug, performance, semantic tokens

#936 fix: "Code | Inspect Code" does not report syntax errors
  src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPDocumentBase.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDiagnosticFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/SeverityMapping.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inspection/LSPLocalInspectionTool.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inspection/LSPLocalInspectionToolBase.java
  src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/inspectionDescriptions/LSPLocalInspectionTool.html
Labels: enhancement, diagnostic

#940 fix: ensure ReadAction when pull diagnostics must be refreshed
  src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
Labels: bug, diagnostic

#942 feat: Create a Docker Language Server template
  docs/images/user-defined-ls/docker-language-server/console-output.png
  docs/images/user-defined-ls/docker-language-server/dockerfile-problems.png
  docs/images/user-defined-ls/docker-language-server/editing-bake-file.png
  docs/user-defined-ls/docker-language-server.md
  src/main/resources/templates/dockerfile-language-server/clientSettings.json
  src/main/resources/templates/dockerfile-language-server/initializationOptions.json
  src/main/resources/templates/dockerfile-language-server/settings.json
  src/main/resources/templates/dockerfile-language-server/template.json
Labels: user-defined LS

#943 docs: add Docker Language Server link
  docs/UserDefinedLanguageServer.md
Labels: documentation, template-ls
