Repository redhat-developer/lsp4ij, pull requests merged in 2025-05, with the labels that each got.

#1010 chore: changelog for 0.13.0
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#1014 fix: improve dap exception
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
Labels: enhancement

#1015 feat: support for condition DAP breakpoint
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebuggerEditorsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointType.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPExpressionCodeFragment.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java
Labels: enhancement, dap

#1021 fix: activate LSP semantic PsiFile for TEXT language
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/resources/META-INF/plugin.xml
Labels: bug, semantic tokens

#1022 feat: make configurable DAP exceptions
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPExceptionBreakpointsPanel.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfiguration.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DefaultDebugAdapterDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/settings/UserDefinedDebugAdapterServerSettings.java
Labels: enhancement, dap

#1029 docs: improve breakpoint exception doc
  docs/dap/UserGuide.md
  docs/dap/images/DAP_exception_breakpoint_sample.png
  docs/dap/images/DAP_exception_breakpoint_sample_stop.png
Labels: documentation, dap

#1030 fix: take care of invalid DAP source path
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPStackFrame.java
Labels: bug, dap

#1031 feat: support for vscode URI style
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupportBase.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDocumentFeatureSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/callHierarchy/LSPCallHierarchyTreeStructureBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/quickfix/LSPLazyCodeActions.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPGoToDeclarationAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTargetProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java
  src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPGoToImplementationAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/navigation/LSPGotoDeclarationHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPGoToReferenceAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPSelectionRangeSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/signatureHelp/LSPParameterInfoHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPGoToTypeDefinitionAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/typeHierarchy/LSPTypeHierarchyTreeStructureBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceImplementationsSearch.java
  src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceTypeDeclarationProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/uri/UriFormatter.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSupport.java
  src/main/resources/jsonSchema/clientSettings.schema.json
  src/test/java/com/redhat/devtools/lsp4ij/internal/uri/UriFormatterTest.java
Labels: bug

#1034 fix: refresh diagnostics on first time
  src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
Labels: bug, diagnostic

#1035 feat: simplify file uri support.
  src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupportBase.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedFileUriSupport.java
Labels: enhancement

#1039 chore: Update build.gradle.kts to support latest version
  build.gradle.kts
Labels: build

#1054 docs: add declarative installer doc
  docs/UserDefinedLanguageServer.md
  docs/UserDefinedLanguageServerTemplate.md
  docs/images/user-defined-ls/InstallUserDefinedLanguageServer.png
  docs/images/user-defined-ls/rust-analyzer/installation_dialog.png
  docs/images/user-defined-ls/rust-analyzer/installation_tab.png
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
  src/main/resources/messages/LanguageServerBundle.properties
Labels: documentation, user-defined LS

#1056 feat: add erlang-ls installer.json
  src/main/resources/templates/lsp/erlang-ls/installer.json
Labels: enhancement, user-defined LS

#1057 docs: How to contribute to User-defined language server template
  docs/UserDefinedLanguageServerTemplate.md
  src/main/resources/templates/lsp/erlang-ls/installer.json
Labels: documentation

#1062 fix: get JSON executable correctly.
  src/main/java/com/redhat/devtools/lsp4ij/JSONUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
Labels: bug

#1064 fix: use "unix" instead of "linux"
  docs/UserDefinedLanguageServerTemplate.md
  src/main/resources/templates/lsp/clangd/installer.json
  src/main/resources/templates/lsp/clojure-lsp/installer.json
  src/main/resources/templates/lsp/erlang-ls/installer.json
  src/main/resources/templates/lsp/rust-analyzer/installer.json
Labels: bug

#1065 fix: fix arch of rust unix installer
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/DownloadTask.java
  src/main/resources/templates/lsp/rust-analyzer/installer.json
Labels: bug

#1070 feat: installer in user defined ls
  src/main/java/com/redhat/devtools/lsp4ij/JSONUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/ServerStatus.java
  src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/NewDebugAdapterServerDialog.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/DeclarativeLanguageServerInstaller.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/LanguageServerInstallerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/InstallerContext.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/InstallerTaskFactoryBase.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/InstallerTaskRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/ServerInstallerDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/ServerInstallerManager.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ConfigureServerTask.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ExecTask.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ExecTaskFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ShowMessageTaskFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/UserDefinedLanguageServerSettings.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/UICommandLineUpdater.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerInstaller.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/ui/InstallerPanel.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/LanguageServerBundle.properties
  src/main/resources/templates/lsp/clangd/installer.json
  src/main/resources/templates/lsp/clojure-lsp/installer.json
  src/main/resources/templates/lsp/erlang-ls/installer.json
  src/main/resources/templates/lsp/gopls/installer.json
  src/main/resources/templates/lsp/rust-analyzer/installer.json
  src/main/resources/templates/lsp/sdl-lsp/installer.json
  src/main/resources/templates/lsp/typescript-language-server/installer.json
Labels: enhancement

#1071 fix: check installation bug
  src/main/java/com/redhat/devtools/lsp4ij/installation/DeclarativeLanguageServerInstaller.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java
  src/main/resources/templates/lsp/jdtls/installer.json
Labels: bug

#1075 feat: Add Astro Language Server
  docs/UserDefinedLanguageServer.md
  docs/UserDefinedLanguageServerTemplate.md
  docs/images/user-defined-ls/astro-ls/demo_ls.gif
  docs/images/user-defined-ls/astro-ls/select_template.png
  docs/user-defined-ls/astro-ls.md
  docs/user-defined-ls/clangd.md
  src/main/java/com/redhat/devtools/lsp4ij/client/IndexAwareLanguageClient.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/InstallerContext.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/InstallerTaskRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/ServerInstallerDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/ServerInstallerManager.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ExecTask.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ExecTaskFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java
  src/main/resources/templates/lsp/astro-ls/clientSettings.json
  src/main/resources/templates/lsp/astro-ls/initializationOptions.json
  src/main/resources/templates/lsp/astro-ls/installer.json
  src/main/resources/templates/lsp/astro-ls/settings.json
  src/main/resources/templates/lsp/astro-ls/settings.schema.json
  src/main/resources/templates/lsp/astro-ls/template.json
  src/main/resources/templates/lsp/typescript-language-server/installer.json
Labels: enhancement, user-defined LS

#1079 feat: add Svelte Language Server
  docs/UserDefinedLanguageServer.md
  docs/images/user-defined-ls/clangd/select_template.png
  docs/images/user-defined-ls/svelte-language-server/select_template.png
  docs/user-defined-ls/astro-ls.md
  docs/user-defined-ls/clangd.md
  docs/user-defined-ls/svelte-language-server.md
  src/main/resources/templates/lsp/svelte-language-server/clientSettings.json
  src/main/resources/templates/lsp/svelte-language-server/initializationOptions.json
  src/main/resources/templates/lsp/svelte-language-server/installer.json
  src/main/resources/templates/lsp/svelte-language-server/settings.json
  src/main/resources/templates/lsp/svelte-language-server/settings.schema.json
  src/main/resources/templates/lsp/svelte-language-server/template.json
Labels: enhancement, user-defined LS

#1080 chore: Bump to 0.14.0-SNAPSHOT
  gradle.properties
Labels: build
