Repository redhat-developer/lsp4ij, pull requests merged in 2025-09, with the labels that each got.

#1254 feat: Support for DAP Disassembly
  docs/dap/DAPSupport.md
  docs/dap/UserGuide.md
  docs/dap/images/DAP_disassembly_demo.gif
  docs/dap/images/DAP_disassembly_view.gif
  docs/dap/images/DAP_open_disassembly_view.png
  docs/dap/images/DAP_runInTerminal_external.png
  docs/dap/images/DAP_runInTerminal_integrated.png
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/BreakpointHandlerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandlerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointType.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPStackFrame.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DAPAlternativeSourceHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassembledInstructionEntry.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyFile.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyFileEditor.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyFileEditorProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyFileRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyFileSystem.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyFileType.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/OpenDisassemblyAction.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/breakpoints/DisassemblyBreakpointHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/breakpoints/DisassemblyBreakpointHandlerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/breakpoints/DisassemblyBreakpointProperties.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/breakpoints/DisassemblyBreakpointType.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/disassembly/breakpoints/DisassemblyBreakpointTypeBase.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPDebuggerEvaluator.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/DAPBundle.properties
  src/test/java/com/redhat/devtools/lsp4ij/dap/disassembly/DisassemblyUtilsTest.java
Labels: enhancement, dap

#1258 feat: Show "Installer" tab only for user defined DAP server
  src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/definitions/userdefined/UserDefinedDebugAdapterDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/definitions/userdefined/UserDefinedDebugAdapterDescriptorFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java
Labels: enhancement, dap

#1260 fix: ignore CancellationException when LSP requets is cancelled
  src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java
Labels: bug

#1264 build: changelog 0.16.0
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: build

#1267 feat: use supportsEvaluateForHovers capability to evaluate variable on hovers
  docs/dap/DAPSupport.md
  src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/BreakpointHandlerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPDebuggerEvaluator.java
Labels: enhancement, dap

#1272 docs: changelog for 0.16.1
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#1279 fix: don't use internal OpenFileDescriptor#navigateInEditor
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/files/DeferredSourcePosition.java
Labels: bug

#1285 feat: Add documentation and template for debugging Dockerfiles with Buildx
  docs/dap/images/buildx-dockerfile/config-01-dap-parameters.png
  docs/dap/images/buildx-dockerfile/features-01-environment.png
  docs/dap/images/buildx-dockerfile/features-02-exec-command.png
  docs/dap/images/buildx-dockerfile/features-02-modify-contents.png
  docs/dap/images/buildx-dockerfile/features-02-shell-reset.png
  docs/dap/images/buildx-dockerfile/setup-01-create-config.png
  docs/dap/images/buildx-dockerfile/setup-02-create-server.png
  docs/dap/images/buildx-dockerfile/setup-03-template-selection.png
  docs/dap/images/buildx-dockerfile/setup-04-env-var.png
  docs/dap/images/buildx-dockerfile/setup-05-file-selection.png
  docs/dap/images/buildx-dockerfile/setup-06-start-debug.png
  docs/dap/user-defined-dap/buildx-dockerfile.md
  src/main/resources/templates/dap/buildx-dockerfile/launch.json
  src/main/resources/templates/dap/buildx-dockerfile/template.json
Labels: documentation, dap

#1290 fix: catch "content changed" error on codelens resolve
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java
Labels: bug

#1288 feat: Add codelldb documentation
  docs/dap/images/codelldb/configuration_tab.png
  docs/dap/images/codelldb/debug_threads_tab.png
  docs/dap/images/codelldb/disassembly.png
  docs/dap/images/codelldb/file_mappings.png
  docs/dap/images/codelldb/generated_executable.png
  docs/dap/images/codelldb/installer_tab.png
  docs/dap/images/codelldb/select_new_server.png
  docs/dap/images/codelldb/select_template.png
  docs/dap/images/codelldb/server_installing.png
  docs/dap/images/codelldb/set_breakpoint.png
  docs/dap/images/codelldb/set_traces.png
  docs/dap/images/codelldb/traces_in_console.png
  docs/dap/user-defined-dap/codelldb.md
  docs/dap/user-defined-dap/go-delve.md
  docs/dap/user-defined-dap/julia.md
  docs/dap/user-defined-dap/python-debugpy.md
  docs/dap/user-defined-dap/ruby-rdbg.md
  docs/dap/user-defined-dap/swift-lldb.md
  docs/dap/user-defined-dap/vscode-js-debug.md
  gradle.properties
Labels: documentation, dap

#1301 fix: use DAP source.path to avoid invalid_frame
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPStackFrame.java
Labels: bug
