Repository redhat-developer/lsp4ij, pull requests merged in 2025-04, with the labels that each got.

#944 fix: ensure that PsiFile.getVirualFile() is not null
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
Labels: bug

#947 docs: show in action "Inspect Code..."
  docs/LSPApi.md
  docs/UserGuide.md
  docs/images/LSPInspectCode.png
  docs/images/LSPInspectCodeCustom.png
Labels: documentation, api-customization

#950 docs: add CDS-LSP to users in README.md
  README.md
Labels: documentation

#952 fix: Docker documentation typos and bullet ordering
  docs/user-defined-ls/docker-language-server.md
Labels: documentation, user-defined LS

#953 feat: Restoring external references search as an opt-in feature that's disabled by default.
  docs/LSPSupport.md
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPReferencesFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedReferencesFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPExternalReferencesFinder.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
  src/main/resources/jsonSchema/clientSettings.schema.json
Labels: enhancement

#954 perf: too many call of DaemonCodeAnalyzer.getInstance(project).restart(file)
  src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPDocumentBase.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensEditorFactoryListener.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java
  src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/DeclarativeInlayHintsEditorFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/InlayHintsEditorFeature.java
Labels: performance

#956 test: tests for LSP diagnostics
  src/test/java/com/redhat/devtools/lsp4ij/features/diagnostics/TypeScriptDiagnosticsTest.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPDiagnosticsFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/impl/LSPCodeInsightTestFixtureImpl.java
Labels: diagnostic, junit-test

#862 test: provide test case for Jakarta quick fixes
  src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/LSPLazyCodeActionIntentionAction.java
  src/test/java/com/redhat/devtools/lsp4ij/features/codeAction/WebFilterQuickFixTest.java
  src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeActionFixtureTestCase.java
  src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java
  src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
Labels: codeAction, junit-test

#958 fix: Cannot select word at given offset error
  src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPSelectionRangeSupport.java
Labels: bug, selectionRange

#960 fix: Integrate fixes from forked (Huly Code) LSP4IJ (null checking)
  src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/features/LSPPsiElement.java
  src/main/java/com/redhat/devtools/lsp4ij/features/LSPPsiElementFactory.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeBlockProvider/LSPCodeBlockProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java
  src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/CompletionProposalTools.java
  src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPGoToDeclarationAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingParams.java
  src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyItemPsiElement.java
  src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyNodeDescriptor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyProviderBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyTreeStructureBase.java
  src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightPsiElement.java
  src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPGoToImplementationAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java
  src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPGoToReferenceAction.java
  src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPGoToTypeDefinitionAction.java
  src/main/java/com/redhat/devtools/lsp4ij/hint/LSPNavigationLinkHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java
Labels: bug

#962 fix: improve snippet escape (from Huly Code)
  src/main/java/com/redhat/devtools/lsp4ij/features/completion/snippet/LspSnippetParser.java
  src/test/java/com/redhat/devtools/lsp4ij/features/completion/snippet/EscapeTest.java
Labels: bug, completion

#965 chore: bump to 0.13.0
  gradle.properties
Labels: bug

#972 fix: dont terminate the debuggee when debug session in attach mode is terminated.
  src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
Labels: bug, dap

#977 feat: report problem in the project view
  docs/LSPApi.md
  docs/UserGuide.md
  docs/images/LSPProblemInProjectView.png
  src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
  src/main/java/com/redhat/devtools/lsp4ij/LSPDocumentBase.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java
  src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDiagnosticFeature.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticUtils.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java
  src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPProblemFileHighlightFilter.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement, diagnostic

#981 fix: check that future is not done to cancel it
  src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java
Labels: bug

#986 fix: use the same new conf of metals.ls vscode
  src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java
  src/main/resources/templates/metals/settings.json
Labels: bug

#987 perf: debounce LSP console tracing
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/LSPPostStartupActivity.java
  src/main/java/com/redhat/devtools/lsp4ij/lifecycle/LanguageServerLifecycleListener.java
Labels: bug, performance

#994 fix: cancel refresh editor future
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDeclarativeInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDocumentRefreshableFeatureSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java
  src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsSupport.java
  src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java
Labels: bug

#995 fix: don't create PsiFile Alarm when support is disposed.
  src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java
Labels: bug

#1000 fix: ensure process is stopped before starting a new process
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
Labels: bug

#1004 fix: Don't force file support creation with document symbol
  src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
Labels: bug, documentSymbols

#1006 fix: Include compose.yaml and compose.yml to the Docker Language Server
  src/main/resources/templates/dockerfile-language-server/template.json
Labels: template-ls
