Repository redhat-developer/lsp4ij, pull requests merged in 2025-06, with the labels that each got.

#1081 feat: add ruby-lsp
  docs/UserDefinedLanguageServer.md
  docs/images/user-defined-ls/ruby-lsp/select_template.png
  docs/user-defined-ls/ruby-lsp.md
  src/main/resources/templates/lsp/ruby-lsp/clientSettings.json
  src/main/resources/templates/lsp/ruby-lsp/initializationOptions.json
  src/main/resources/templates/lsp/ruby-lsp/installer.json
  src/main/resources/templates/lsp/ruby-lsp/settings.json
  src/main/resources/templates/lsp/ruby-lsp/settings.schema.json
  src/main/resources/templates/lsp/ruby-lsp/template.json
Labels: enhancement, user-defined LS

#1086 feat: add installer.json for dockerfile-language-server
  src/main/resources/templates/lsp/dockerfile-language-server/installer.json
Labels: enhancement, user-defined LS

#1087 fix: Correct the name of the Docker Language Server
  src/main/resources/templates/lsp/dockerfile-language-server/installer.json
Labels: bug, user-defined LS

#1088 fix: Rename the folder to match the name of the language server
  src/main/resources/templates/lsp/docker-language-server/clientSettings.json
  src/main/resources/templates/lsp/docker-language-server/initializationOptions.json
  src/main/resources/templates/lsp/docker-language-server/initializationOptions.schema.json
  src/main/resources/templates/lsp/docker-language-server/installer.json
  src/main/resources/templates/lsp/docker-language-server/settings.json
  src/main/resources/templates/lsp/docker-language-server/template.json
Labels: bug

#1090 feat: update JSON schema, settings as flat for all LSP
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/client/SettingsHelper.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/UserDefinedLanguageServerSettings.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateDeserializer.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/UICommandLineUpdater.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java
  src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java
  src/main/resources/messages/LanguageServerBundle.properties
  src/main/resources/templates/lsp/astro-ls/settings.json
  src/main/resources/templates/lsp/astro-ls/settings.schema.json
  src/main/resources/templates/lsp/astro-ls/template.json
  src/main/resources/templates/lsp/clangd/settings.json
  src/main/resources/templates/lsp/clangd/settings.schema.json
  src/main/resources/templates/lsp/clangd/template.json
  src/main/resources/templates/lsp/clojure-lsp/settings.json
  src/main/resources/templates/lsp/clojure-lsp/settings.schema.json
  src/main/resources/templates/lsp/clojure-lsp/template.json
  src/main/resources/templates/lsp/gopls/settings.json
  src/main/resources/templates/lsp/gopls/settings.schema.json
  src/main/resources/templates/lsp/gopls/template.json
  src/main/resources/templates/lsp/julia/settings.json
  src/main/resources/templates/lsp/julia/settings.schema.json
  src/main/resources/templates/lsp/julia/template.json
  src/main/resources/templates/lsp/metals/settings.json
  src/main/resources/templates/lsp/metals/settings.schema.json
  src/main/resources/templates/lsp/metals/template.json
  src/main/resources/templates/lsp/ruby-lsp/settings.json
  src/main/resources/templates/lsp/ruby-lsp/settings.schema.json
  src/main/resources/templates/lsp/ruby-lsp/template.json
  src/main/resources/templates/lsp/rust-analyzer/settings.json
  src/main/resources/templates/lsp/rust-analyzer/settings.schema.json
  src/main/resources/templates/lsp/rust-analyzer/template.json
  src/main/resources/templates/lsp/sourcekit-lsp/settings.json
  src/main/resources/templates/lsp/sourcekit-lsp/settings.schema.json
  src/main/resources/templates/lsp/sourcekit-lsp/template.json
  src/main/resources/templates/lsp/svelte-language-server/settings.json
  src/main/resources/templates/lsp/svelte-language-server/settings.schema.json
  src/main/resources/templates/lsp/svelte-language-server/template.json
  src/main/resources/templates/lsp/vscode-css-language-server/settings.json
  src/main/resources/templates/lsp/vscode-css-language-server/settings.schema.json
  src/main/resources/templates/lsp/vscode-css-language-server/template.json
  src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelper_findSettingsTest.java
  src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelper_parseJsonTest.java
  src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerDefinitionSerializerTest.java
  src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManagerTest.java
Labels: enhancement, user-defined LS

#1094 feat: add luau-lsp
  src/main/java/com/redhat/devtools/lsp4ij/commands/editor/TriggerCommandAction.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/editor/TriggerParameterHintsAction.java
  src/main/java/com/redhat/devtools/lsp4ij/commands/editor/TriggerSuggestAction.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/templates/lsp/luau-lsp/clientSettings.json
  src/main/resources/templates/lsp/luau-lsp/installer.json
  src/main/resources/templates/lsp/luau-lsp/settings.json
  src/main/resources/templates/lsp/luau-lsp/settings.schema.json
  src/main/resources/templates/lsp/luau-lsp/template.json
Labels: enhancement, user-defined LS

#1100 fix: show LSP logs again
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
Labels: bug

#1102 fix: ensure starting server when installation is terminated
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerManager.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerTreeRenderer.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/LanguageServerInstallerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/UICommandLineUpdater.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java
Labels: bug

#1104 feat: add sourcekit lsp installer
  src/main/resources/templates/lsp/metals/installer.json
  src/main/resources/templates/lsp/sourcekit-lsp/installer.json
Labels: enhancement, user-defined LS

#1105 feat: improve gopls installer
  src/main/resources/templates/lsp/gopls/installer.json
Labels: enhancement, user-defined LS

#1106 feat: add Dart LSP
  docs/UserDefinedLanguageServer.md
  docs/user-defined-ls/dart-lsp.md
  src/main/resources/templates/lsp/dart-lsp/clientSettings.json
  src/main/resources/templates/lsp/dart-lsp/initializationOptions.json
  src/main/resources/templates/lsp/dart-lsp/installer.json
  src/main/resources/templates/lsp/dart-lsp/settings.json
  src/main/resources/templates/lsp/dart-lsp/settings.schema.json
  src/main/resources/templates/lsp/dart-lsp/template.json
  src/main/resources/templates/lsp/sourcekit-lsp/installer.json
Labels: enhancement, user-defined LS

#1110 feat: add Camel Language Server
  src/main/resources/templates/lsp/camel-lsp-server/clientSettings.json
  src/main/resources/templates/lsp/camel-lsp-server/installer.json
  src/main/resources/templates/lsp/camel-lsp-server/settings.json
  src/main/resources/templates/lsp/camel-lsp-server/settings.schema.json
  src/main/resources/templates/lsp/camel-lsp-server/template.json
Labels: enhancement, user-defined LS

#1111 fix: remove unused camel JSON properties
  src/main/resources/templates/lsp/camel-lsp-server/settings.json
  src/main/resources/templates/lsp/camel-lsp-server/settings.schema.json
Labels: bug, user-defined LS

#1119 feat: Promote installation of LSP4IJ template when editor is opened
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
  src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerFileAssociation.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerFileNamePatternMapping.java
  src/main/java/com/redhat/devtools/lsp4ij/templates/ServerTemplate.java
  src/main/java/com/redhat/devtools/lsp4ij/ui/LanguageServerSuggestionEditorNotificationProvider.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/LanguageServerBundle.properties
  src/main/resources/messages/LanguageServerBundle_zh_CN.properties
Labels: enhancement, user-defined LS

#1120 feat: Provide Install / Reinstall actions from the LSP explorer
  docs/DeveloperGuide.md
  docs/LSPApi.md
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerManager.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/actions/InstallServerAction.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/actions/InstallServerActionBase.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/actions/ReinstallServerAction.java
  src/main/java/com/redhat/devtools/lsp4ij/dap/definitions/userdefined/UserDefinedDebugAdapterServerInstaller.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/LanguageServerInstallerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallationContext.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstaller.java
  src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java
  src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerInstaller.java
  src/main/resources/messages/LanguageServerBundle.properties
Labels: enhancement

#1121 fix: wait for stop termination before launching install
  src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
  src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
Labels: bug

#1127 chore: add changelog for 0.14.0
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#1129 docs: Add Astro documentation
  docs/images/user-defined-ls/astro-ls/language_server_installing.png
  docs/images/user-defined-ls/astro-ls/new_language_server_dialog.png
  docs/images/user-defined-ls/astro-ls/open_file.png
  docs/images/user-defined-ls/astro-ls/select_template.png
  docs/images/user-defined-ls/textmate_bundles_settings.png
  docs/user-defined-ls/astro-ls.md
Labels: documentation

#1130 docs: Add Astro documentation
  docs/user-defined-ls/astro-ls.md
Labels: documentation

#1142 fix: set working dir to node_modules dir.
  src/main/resources/templates/lsp/astro-ls/installer.json
  src/main/resources/templates/lsp/svelte-language-server/installer.json
  src/main/resources/templates/lsp/typescript-language-server/installer.json
Labels: bug

#1145 feat: use vscode-langservers-extracted for CSS language server
  src/main/resources/templates/lsp/vscode-css-language-server/installer.json
Labels: enhancement, install

#1147 feat: set vscode html ls as dev
  src/main/resources/templates/lsp/vscode-html-language-server/template.json
Labels: enhancement

#1151 feat: refresh editor notification for all opened files.
  src/main/java/com/redhat/devtools/lsp4ij/ui/LanguageServerSuggestionEditorNotificationProvider.java
Labels: enhancement

#1154 chore: changelog 0.14.1
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#1156 feat: add terraform ls
  docs/UserDefinedLanguageServer.md
  docs/images/user-defined-ls/terraform-ls/demo_ls.gif
  docs/images/user-defined-ls/terraform-ls/installer_tab.png
  docs/images/user-defined-ls/terraform-ls/language_server_installing.png
  docs/images/user-defined-ls/terraform-ls/new_language_server_dialog.png
  docs/images/user-defined-ls/terraform-ls/open_file.png
  docs/user-defined-ls/terraform-ls.md
  src/main/resources/templates/lsp/terraform-ls/clientSettings.json
  src/main/resources/templates/lsp/terraform-ls/installer.json
  src/main/resources/templates/lsp/terraform-ls/settings.json
  src/main/resources/templates/lsp/terraform-ls/settings.schema.json
  src/main/resources/templates/lsp/terraform-ls/template.json
Labels: enhancement, user-defined LS

#1158 chore: changelog for 0.14.2
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#1162 fix: empty section must return the full server config
  src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
Labels: bug

#1163 feat: add ESLint as user defined ls
  docs/UserDefinedLanguageServer.md
  docs/user-defined-ls/vscode-eslint-language-server.md
  src/main/resources/templates/lsp/vscode-eslint-language-server/installer.json
  src/main/resources/templates/lsp/vscode-eslint-language-server/settings.json
  src/main/resources/templates/lsp/vscode-eslint-language-server/settings.schema.json
  src/main/resources/templates/lsp/vscode-eslint-language-server/template.json
Labels: enhancement, user-defined LS
